language: go



services:
- postgresql

addons:
  postgresql: "10"
  apt:
      packages:
      - postgresql-10
      - postgresql-client-10

before_script:
- psql -c 'create database travis_ci_test;' -U postgres

env:
  global:
  - PGPORT=5433


go:
- "1.10.3"

install:
- go get -u



